# Generated by Django 3.1 on 2020-08-16 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='moduleName',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
